version: 1.7

environment:
  - APM_PORT=${APM_PORT}
  - APM_HOSTNAME=${APM_HOSTNAME}
  - APM_SA_NAME=${APM_SA_NAME}
  - APM_KEYVAULT_NAME=${APM_KEYVAULT_NAME}
  - APM_MASTER_KEY_ID=${APM_MASTER_KEY_ID}
  - MAA_ENDPOINT=${MAA_ENDPOINT}
