version: 1.7

environment:
  - APM_PORT=${APM_PORT}
  - APM_HOSTNAME=${APM_HOSTNAME}
  - APM_SA_NAME=${APM_SA_NAME}
  - APM_KEYVAULT_NAME=${APM_KEYVAULT_NAME}
  - APM_MK_ID=${APM_MK_ID}
  - MAA_ENDPOINT=${MAA_ENDPOINT}
